name: Update Data Package

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  # schedule:
  #  - cron: '17,34,57 7-18 * * *'

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    name: Update Data Package
    steps:
      - uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64
      - name: Install Poetry
        uses: snok/install-poetry@v1.1.4
        with:
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Load cached venv
        id: cached-poetry-dependencies
        uses: actions/cache@v2
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
      - name: Install dependencies
        if: steps.cached-poetry-dependencies.outputs.cache-hit != 'true'
        run: poetry install --no-interaction --no-root
      - name: Install libraries
        run: poetry install --no-interaction
      - run: |
          source .venv/bin/activate
          python vaccination.py
      - name: push
        uses: actions-x/commit@v2
